// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteProperty(ctx context.Context, id uuid.UUID) error
	GetPropertiesByOwnerID(ctx context.Context, arg GetPropertiesByOwnerIDParams) ([]Property, error)
	GetPropertyByID(ctx context.Context, id uuid.UUID) (Property, error)
	InsertProperty(ctx context.Context, arg InsertPropertyParams) (Property, error)
	ListProperties(ctx context.Context, arg ListPropertiesParams) ([]Property, error)
	UpdateProperty(ctx context.Context, arg UpdatePropertyParams) error
}

var _ Querier = (*Queries)(nil)
