// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddPropertyAmenity(ctx context.Context, arg AddPropertyAmenityParams) error
	AddPropertyImage(ctx context.Context, arg AddPropertyImageParams) (PropertyImage, error)
	BulkSetPropertyAvailabilityStatus(ctx context.Context, arg BulkSetPropertyAvailabilityStatusParams) error
	ClearUserSearchHistory(ctx context.Context, userID uuid.UUID) error
	CountProperties(ctx context.Context, arg CountPropertiesParams) (int64, error)
	CreateAmenity(ctx context.Context, arg CreateAmenityParams) (Amenity, error)
	CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error)
	CreatePropertyDetail(ctx context.Context, arg CreatePropertyDetailParams) (PropertyDetail, error)
	CreatePropertyNeighborhood(ctx context.Context, arg CreatePropertyNeighborhoodParams) (PropertyNeighborhood, error)
	DeleteAmenity(ctx context.Context, id uuid.UUID) error
	DeleteProperty(ctx context.Context, id uuid.UUID) error
	DeletePropertyImage(ctx context.Context, id uuid.UUID) error
	DeleteSearchHistory(ctx context.Context, arg DeleteSearchHistoryParams) error
	GetAmenityByID(ctx context.Context, id uuid.UUID) (Amenity, error)
	GetPropertiesByAmenity(ctx context.Context, arg GetPropertiesByAmenityParams) ([]Property, error)
	GetPropertiesByMultipleAmenities(ctx context.Context, arg GetPropertiesByMultipleAmenitiesParams) ([]GetPropertiesByMultipleAmenitiesRow, error)
	GetPropertiesByOwner(ctx context.Context, arg GetPropertiesByOwnerParams) ([]Property, error)
	GetPropertyAmenities(ctx context.Context, propertyID uuid.UUID) ([]GetPropertyAmenitiesRow, error)
	GetPropertyAvailability(ctx context.Context, arg GetPropertyAvailabilityParams) ([]PropertyAvailability, error)
	GetPropertyByID(ctx context.Context, id uuid.UUID) (Property, error)
	GetPropertyDetailByPropertyID(ctx context.Context, propertyID uuid.UUID) (PropertyDetail, error)
	GetPropertyNeighborhood(ctx context.Context, propertyID uuid.UUID) (PropertyNeighborhood, error)
	GetPropertyViewStats(ctx context.Context, propertyID uuid.UUID) (GetPropertyViewStatsRow, error)
	GetPropertyWithAllDetails(ctx context.Context, id uuid.UUID) (GetPropertyWithAllDetailsRow, error)
	GetRecentlyViewedProperties(ctx context.Context, arg GetRecentlyViewedPropertiesParams) ([]GetRecentlyViewedPropertiesRow, error)
	GetUserSearchHistory(ctx context.Context, arg GetUserSearchHistoryParams) ([]SearchHistory, error)
	ListAmenities(ctx context.Context, dollar_1 AmenityCategory) ([]Amenity, error)
	ListProperties(ctx context.Context, arg ListPropertiesParams) ([]ListPropertiesRow, error)
	ListPropertyImages(ctx context.Context, propertyID uuid.UUID) ([]PropertyImage, error)
	RecordPropertyView(ctx context.Context, arg RecordPropertyViewParams) (PropertyView, error)
	RemoveAllPropertyAmenities(ctx context.Context, propertyID uuid.UUID) error
	RemovePropertyAmenity(ctx context.Context, arg RemovePropertyAmenityParams) error
	SaveSearchHistory(ctx context.Context, arg SaveSearchHistoryParams) (SearchHistory, error)
	SearchPropertiesWithDetails(ctx context.Context, arg SearchPropertiesWithDetailsParams) ([]SearchPropertiesWithDetailsRow, error)
	SetPrimaryPropertyImage(ctx context.Context, arg SetPrimaryPropertyImageParams) error
	SetPropertyAvailability(ctx context.Context, arg SetPropertyAvailabilityParams) (PropertyAvailability, error)
	UpdateAmenity(ctx context.Context, arg UpdateAmenityParams) (Amenity, error)
	UpdateProperty(ctx context.Context, arg UpdatePropertyParams) (Property, error)
	UpdatePropertyDetail(ctx context.Context, arg UpdatePropertyDetailParams) (PropertyDetail, error)
	UpdatePropertyImage(ctx context.Context, arg UpdatePropertyImageParams) (PropertyImage, error)
	UpdatePropertyNeighborhood(ctx context.Context, arg UpdatePropertyNeighborhoodParams) (PropertyNeighborhood, error)
	UpdatePropertyStatus(ctx context.Context, arg UpdatePropertyStatusParams) (Property, error)
}

var _ Querier = (*Queries)(nil)
