// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createLoginHistoryEntry = `-- name: CreateLoginHistoryEntry :one
INSERT INTO sessions (
    session_id, user_id, ip_address, user_agent
) VALUES (
    $1, $2, $3, $4
) RETURNING session_id, user_id, token, created_at, expires_at, last_activity, ip_address, user_agent, is_active, revoked_at, device_info
`

type CreateLoginHistoryEntryParams struct {
	SessionID uuid.UUID      `json:"session_id"`
	UserID    uuid.UUID      `json:"user_id"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
}

func (q *Queries) CreateLoginHistoryEntry(ctx context.Context, arg CreateLoginHistoryEntryParams) (Sessions, error) {
	row := q.db.QueryRowContext(ctx, createLoginHistoryEntry,
		arg.SessionID,
		arg.UserID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i Sessions
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastActivity,
		&i.IpAddress,
		&i.UserAgent,
		&i.IsActive,
		&i.RevokedAt,
		&i.DeviceInfo,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    session_id,
    user_id,
    token,
    expires_at,
    last_activity,
    ip_address,
    user_agent,
    is_active,
    revoked_at,
    device_info
) VALUES (
    $1, -- session_id
    $2, -- user_id
    $3, -- token
    $4, -- expires_at
    $5, -- last_activity
    $6, -- ip_address
    $7, -- user_agent
    $8, -- is_active
    $9, -- revoked_at
    $10 -- device_info
) RETURNING session_id, user_id, token, created_at, expires_at, last_activity, ip_address, user_agent, is_active, revoked_at, device_info
`

type CreateSessionParams struct {
	SessionID    uuid.UUID             `json:"session_id"`
	UserID       uuid.UUID             `json:"user_id"`
	Token        string                `json:"token"`
	ExpiresAt    time.Time             `json:"expires_at"`
	LastActivity time.Time             `json:"last_activity"`
	IpAddress    sql.NullString        `json:"ip_address"`
	UserAgent    sql.NullString        `json:"user_agent"`
	IsActive     bool                  `json:"is_active"`
	RevokedAt    sql.NullTime          `json:"revoked_at"`
	DeviceInfo   pqtype.NullRawMessage `json:"device_info"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Sessions, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.SessionID,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
		arg.LastActivity,
		arg.IpAddress,
		arg.UserAgent,
		arg.IsActive,
		arg.RevokedAt,
		arg.DeviceInfo,
	)
	var i Sessions
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastActivity,
		&i.IpAddress,
		&i.UserAgent,
		&i.IsActive,
		&i.RevokedAt,
		&i.DeviceInfo,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE session_id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSession, sessionID)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT session_id, user_id, token, created_at, expires_at, last_activity, ip_address, user_agent, is_active, revoked_at, device_info FROM sessions
WHERE session_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, sessionID uuid.UUID) (Sessions, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, sessionID)
	var i Sessions
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastActivity,
		&i.IpAddress,
		&i.UserAgent,
		&i.IsActive,
		&i.RevokedAt,
		&i.DeviceInfo,
	)
	return i, err
}

const getSessionByUserID = `-- name: GetSessionByUserID :one
SELECT session_id, user_id, token, created_at, expires_at, last_activity, ip_address, user_agent, is_active, revoked_at, device_info FROM sessions
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetSessionByUserID(ctx context.Context, userID uuid.UUID) (Sessions, error) {
	row := q.db.QueryRowContext(ctx, getSessionByUserID, userID)
	var i Sessions
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastActivity,
		&i.IpAddress,
		&i.UserAgent,
		&i.IsActive,
		&i.RevokedAt,
		&i.DeviceInfo,
	)
	return i, err
}

const getSessionsByUserID = `-- name: GetSessionsByUserID :many
SELECT session_id, user_id, token, created_at, expires_at, last_activity, ip_address, user_agent, is_active, revoked_at, device_info FROM sessions 
WHERE user_id = $1 
ORDER BY created_at DESC
`

func (q *Queries) GetSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]Sessions, error) {
	rows, err := q.db.QueryContext(ctx, getSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sessions{}
	for rows.Next() {
		var i Sessions
		if err := rows.Scan(
			&i.SessionID,
			&i.UserID,
			&i.Token,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastActivity,
			&i.IpAddress,
			&i.UserAgent,
			&i.IsActive,
			&i.RevokedAt,
			&i.DeviceInfo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET
    is_active = false,
    revoked_at = now()
WHERE user_id = $1 AND is_active = true
`

func (q *Queries) RevokeSession(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeSession, userID)
	return err
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET
    token = COALESCE($1, token),
    expires_at = COALESCE($2, expires_at),
    last_activity = COALESCE($3, last_activity),
    ip_address = COALESCE($4, ip_address),
    user_agent = COALESCE($5, user_agent),
    is_active = COALESCE($6, is_active),
    revoked_at = COALESCE($7, revoked_at),
    device_info = COALESCE($8, device_info)
WHERE user_id = $9
RETURNING session_id, user_id, token, created_at, expires_at, last_activity, ip_address, user_agent, is_active, revoked_at, device_info
`

type UpdateSessionParams struct {
	Token        string                `json:"token"`
	ExpiresAt    time.Time             `json:"expires_at"`
	LastActivity time.Time             `json:"last_activity"`
	IpAddress    sql.NullString        `json:"ip_address"`
	UserAgent    sql.NullString        `json:"user_agent"`
	IsActive     bool                  `json:"is_active"`
	RevokedAt    sql.NullTime          `json:"revoked_at"`
	DeviceInfo   pqtype.NullRawMessage `json:"device_info"`
	UserID       uuid.UUID             `json:"user_id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Sessions, error) {
	row := q.db.QueryRowContext(ctx, updateSession,
		arg.Token,
		arg.ExpiresAt,
		arg.LastActivity,
		arg.IpAddress,
		arg.UserAgent,
		arg.IsActive,
		arg.RevokedAt,
		arg.DeviceInfo,
		arg.UserID,
	)
	var i Sessions
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastActivity,
		&i.IpAddress,
		&i.UserAgent,
		&i.IsActive,
		&i.RevokedAt,
		&i.DeviceInfo,
	)
	return i, err
}

const updateSessionActivity = `-- name: UpdateSessionActivity :exec
UPDATE sessions
SET
    last_activity = $1,
    is_active = $2
WHERE session_id = $3
`

type UpdateSessionActivityParams struct {
	LastActivity time.Time `json:"last_activity"`
	IsActive     bool      `json:"is_active"`
	SessionID    uuid.UUID `json:"session_id"`
}

func (q *Queries) UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionActivity, arg.LastActivity, arg.IsActive, arg.SessionID)
	return err
}
